---
# tasks file for users
- name: Create user group 
  group:
    name: "{{ groupname }}"
    state: present

- name: Adding wheel group for sudo access
  copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
   
- name: creating users and generate SSH key 
  user:
    name: "{{ item }}"
    state: present
    append: yes
    shell: /bin/bash
    group: "{{ groupname }}"
    groups: wheel
    home: /home/{{item}} 
  loop: "{{ userlist }}"

- name: create users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  loop: "{{ userlist }}"